### ISSUE TITLE
Not working for more than one server

### ISSUE THREAD

**Issue by arey0pushpa** [markap/socket.io-scale#2]
/usr/local/lib/node_modules/socket.io/lib/manager.js:104
  server.on('error', function(err) {
         ^
TypeError: Object 8099 has no method 'on'

even first one while passing process.argv[2] argument as a port not working . Help ..

**Comment by markap** [comment]
port must be of type number.

should work again.

**Comment by arey0pushpa** [comment]
Txs figured it out after one - two web searches . thank you .

**Comment by markap** [comment]
Great!
