### ISSUE TITLE
cannot get it working

### ISSUE THREAD

**Issue by flyon** [markap/socket.io-scale#4]
socket.io/lib/stores/redis does not exist anymore in recent versions of socket.io.

The suggested solution in the other issue to use socket.io-redis is not complete. 
I would really really like any easy working exampe of redis with multiple socket.io instances! If you could help that would be greatly apriciated.

**Comment by markap** [comment]
Does this help you? https://github.com/markap/socket.io-scale/issues/3

**Comment by flyon** [comment]
no, like I said, it mentions socket.io-redis, but you cannot use that as a simple drop-in replacement. I've got socket.io-redis to work with [this example code](https://github.com/socketio/socket.io-redis/issues/117), but not with the code in this repository.
